name: Deploy Nuxt App to GitHub Pages (Bun)

on:
  push:
    branches:
      - main
      - feature/github-pages

env:
  BASE_URL: https://quirinecker.github.io/dayplanner

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: |
          cd web
          bun install

      - name: Generate static site
        run: |
          cd web
          bun run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/.output/public
          publish_branch: gh-pages

